//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by SDKDemo.rc
//
#define IDC_BTN_PHOTO                   4
#define IDC_BTN_RECORD                  5
#define IDC_BTN_PLAYBACK                6
#define IDC_BTN_SEARCH                  7
#define IDC_BTN_TALK                    8
#define IDC_BTN_CHECK                   8
#define IDC_BTN_SEL                     9
#define IDC_BTN_NET_SNAP                10
#define IDM_ABOUTBOX                    0x0010
#define IDD_ABOUTBOX                    100
#define IDS_ABOUTBOX                    101
#define IDD_SDKDEMO_DIALOG              102
#define IDR_MAINFRAME                   128
#define IDD_PLAYBACK_DIALOG             129
#define IDB_TALK                        130
#define IDB_REC                         131
#define IDD_TIME_DIALOG                 132
#define IDD_COVER_DLG                   133
#define IDD_OSD_DLG                     134
#define IDD_NET_DLG                     136
#define IDD_WIFI_DLG                    137
#define IDD_PTZ_DLG                     138
#define IDD_AUDIO_DLG                   139
#define IDD_INPUT_DLG                   140
#define IDD_OTHER_DLG                   141
#define IDD_VIDEO_DLG                   142
#define IDC_VIEW                        1000
#define IDC_BTN_UP                      1001
#define IDC_BTN_DOWN                    1002
#define IDC_BTN_PTZSTOP                 1003
#define IDC_BTN_LEFT                    1004
#define IDC_BTN_RIGHT                   1005
#define IDC_EDIT_USERNAME               1007
#define IDC_BTN_OPEN                    1007
#define IDC_EDIT_PASSWORD               1008
#define IDC_BTN_PLAY                    1008
#define IDC_EDIT_PORT                   1009
#define IDC_BTN_STOP                    1009
#define IDC_BTN_PTZZOOMIN               1010
#define IDC_SLIDER_POS                  1010
#define IDC_BTN_PTZZOOMOUT              1011
#define IDC_BTN_FRAME                   1011
#define IDC_BTN_PTZHOME                 1012
#define IDC_BTN_PTZCRUISE_H             1013
#define IDC_BTN_PTZCRUISE_V             1014
#define IDC_BTN_IRISBIG                 1015
#define IDC_BTN_PRESET                  1016
#define IDC_BTN_PRECALL                 1017
#define IDC_EDIT_PRESET                 1018
#define IDC_BTN_PTZTrans                1019
#define IDC_EDIT_PTZDATA                1020
#define IDC_SLIDER_BRIGHT               1021
#define IDC_SLIDER_SATURATION           1022
#define IDC_SLIDER_CONTRAST             1023
#define IDC_SLIDER_HUE                  1024
#define IDC_BTN_RESTORE                 1025
#define IDC_BTN_DEFAULT                 1025
#define IDC_EDIT_DEVTYPE                1026
#define IDC_EDIT_VENDOR                 1027
#define IDC_COMBO_RESOLUTION            1028
#define IDC_COMBO_FREQUENCY             1029
#define IDC_BTN_SETSIZE                 1030
#define IDC_EDIT_TIME                   1031
#define IDC_COMBO_RESOLUTION2           1031
#define IDC_BTN_RBTIME                  1032
#define IDC_COMBO_FREQUENCY2            1032
#define IDC_CHECK_TIMEOSD               1033
#define IDC_BTN_IRISSMALL               1033
#define IDC_BTN_SETSIZE2                1033
#define IDC_CHECK_NAMEOSD               1034
#define IDC_BTN_FOCUSIN                 1034
#define IDC_EDIT_OSDNAME                1035
#define IDC_BTN_FOCUSOUT                1035
#define IDC_BTN_SETOSD                  1036
#define IDC_CHECK_SHOWINFO              1037
#define IDC_BTN_SETNAME                 1037
#define IDC_CHECK_SHOWALARM             1038
#define IDC_SLIDER_VOLUME               1039
#define IDC_BTN_SETMUTE                 1040
#define IDC_CHECK_FLIP                  1041
#define IDC_CHECK_MIRROR                1042
#define IDC_COMBO_NIGHTVISION           1043
#define IDC_COMBO_WHITEBALANCE          1044
#define IDC_CHECK_EDITALARM             1045
#define IDC_BTN_SETDISP                 1046
#define IDC_EDIT_BITRATE                1047
#define IDC_EDIT_IFRAME                 1048
#define IDC_COMBO_QUALITY               1049
#define IDC_BTN_SETVIDEO                1050
#define IDC_BTN_CLEARMD                 1051
#define IDC_EDIT_BITRATE2               1051
#define IDC_BTN_SETMD                   1052
#define IDC_COMBO_QUALITY2              1052
#define IDC_BTN_NIGHT                   1053
#define IDC_BTN_SETVIDEO2               1053
#define IDC_COMBO_SERVER                1054
#define IDC_EDIT_IFRAME2                1054
#define IDC_BTN_SETFQ                   1055
#define IDC_StaticScopeBitrate          1056
#define IDC_ST_SHOWINFO                 1057
#define IDC_StaticScopeBitrate2         1057
#define IDC_BTN_SETEA                   1058
#define IDC_BTN_SETFQ2                  1058
#define IDC_LIST_MDINFO                 1059
#define IDC_COMBO_FRAMERATE             1061
#define IDC_BTN_VIDEO                   1062
#define IDC_COMBO_FRAMERATE2            1062
#define IDC_BTN_AUDIO                   1063
#define IDC_BTN_PTZ                     1064
#define IDC_BTN_MD                      1065
#define IDC_BTN_OTHER                   1066
#define IDC_BTN_PTZCTRL                 1067
#define IDC_BTN_COLOR                   1068
#define IDC_COMBO_AUFORMAT              1071
#define IDC_COMBO_AUINPUT               1072
#define IDC_BTN_SETAUDIO                1073
#define IDC_BTN_SETINPUT                1074
#define IDC_BTN_SETPTZ                  1075
#define IDC_COMBO_AUFORMAT2             1075
#define IDC_EDIT_ADDRESS                1076
#define IDC_BTN_SETAUDIO2               1076
#define IDC_BTN_SETOUTPUT               1076
#define IDC_COMBO_PROTOCOL              1077
#define IDC_COMBO_AERA                  1078
#define IDC_COMBO_DATABIT               1079
#define IDC_COMBO_STOPBIT               1080
#define IDC_COMBO_PARITY                1081
#define IDC_COMBO_BAUD                  1082
#define IDC_CHECK_MD                    1083
#define IDC_CHECK_MD1                   1083
#define IDC_COMBO_AUSWITCH              1084
#define IDC_EDIT_X                      1085
#define IDC_COMBO_EA                    1085
#define IDC_COMBO_AUSWITCH2             1085
#define IDC_EDIT_Y                      1086
#define IDC_COMBO_EAM                   1086
#define IDC_EDIT_WIDTH                  1087
#define IDC_EDIT_HEIGHT                 1088
#define IDC_COMBO_LCBR                  1089
#define IDC_COMBO_SENSITIVITY           1090
#define IDC_COMBO_LCBR2                 1090
#define IDC_CHECK_MD2                   1091
#define IDC_CONNECT                     1092
#define IDC_BTN_CONNECT                 1092
#define IDC_T_AERA                      1093
#define IDC_T_AERA1                     1093
#define IDC_T_MDENABLE                  1094
#define IDC_T_SENSITIVITY               1095
#define IDC_T_X                         1096
#define IDC_T_Y                         1097
#define IDC_T_WIDTH                     1098
#define IDC_T_HEIGHT                    1099
#define IDC_T_ADDRESS                   1100
#define IDC_T_PROTOCOL                  1101
#define IDC_T_BAUD                      1102
#define IDC_T_DATABIT                   1103
#define IDC_T_STOPBIT                   1104
#define IDC_T_PARITY                    1105
#define IDC_T_AUSWITCH                  1106
#define IDC_T_AUFORMAT                  1107
#define IDC_T_AUINPUT                   1108
#define IDC_T_CCD                       1109
#define IDC_T_AUSWITCH2                 1109
#define IDC_T_AUINPUT2                  1109
#define IDC_T_WHITEBALANCE              1110
#define IDC_T_AUFORMAT2                 1110
#define IDC_T_AUINPUT3                  1110
#define IDC_T_NIGHTVISION               1111
#define IDC_T_TIME                      1112
#define IDC_T_RESOLUTION                1113
#define IDC_T_FREQUENCY                 1114
#define IDC_T_BITRATE                   1115
#define IDC_T_FRAMERATE                 1116
#define IDC_T_IFRAME                    1117
#define IDC_T_LCBR                      1118
#define IDC_T_QUALITY                   1119
#define IDC_T_OSDNAME                   1120
#define IDC_T_RESOLUTION2               1120
#define IDC_T_INTERVAL                  1121
#define IDC_COMBO_RATE                  1122
#define IDC_CHECK_MD3                   1122
#define IDC_T_FREQUENCY2                1122
#define IDC_SHOW_TIME                   1123
#define IDC_CHECK_MD4                   1123
#define IDC_T_BITRATE2                  1123
#define IDC_SLIDER_SENSITIVITY1         1124
#define IDC_T_FRAMERATE2                1124
#define IDC_SLIDER_SENSITIVITY2         1125
#define IDC_T_QUALITY2                  1125
#define IDC_SLIDER_SENSITIVITY3         1126
#define IDC_T_LCBR2                     1126
#define IDC_SLIDER_SENSITIVITY4         1127
#define IDC_T_IFRAME2                   1127
#define IDC_T_AERA2                     1128
#define IDC_T_INTERVAL2                 1128
#define IDC_T_MD1                       1129
#define IDC_T_MD2                       1130
#define IDC_T_MD3                       1131
#define IDC_T_MD4                       1132
#define IDC_T_AERA3                     1133
#define IDC_T_AERA4                     1134
#define IDC_EDIT_SPEED                  1135
#define IDC_COMBO_TYPE                  1136
#define IDC_COMBO_SPEED                 1137
#define IDC_COMBO_PTZTYPE               1138
#define IDC_T_BRIGHT                    1139
#define IDC_T_SATURATION                1140
#define IDC_T_CONTRAST                  1141
#define IDC_T_HUE                       1142
#define IDC_T_HDHUE                     1143
#define IDC_T_ZOOM                      1144
#define IDC_T_IRIS                      1145
#define IDC_T_SPEED                     1146
#define IDC_T_TYPE                      1147
#define IDC_COMBO_RECTYPE               1148
#define IDC_BTN_REBOOT                  1149
#define IDC_BTN_RESET                   1150
#define IDC_BTN_SETTIME                 1151
#define IDC_BTN_SETCOVER                1152
#define IDC_BTN_SET                     1153
#define IDC_BTN_OSD                     1153
#define IDC_CHECK_SYNC                  1154
#define IDC_T_FOCUS                     1154
#define IDC_BTN_NET                     1155
#define IDC_BTN_WIFI                    1156
#define IDC_DT_DATE                     1157
#define IDC_DT_TIME                     1158
#define IDC_EDIT_X1                     1158
#define IDC_EDIT_Y1                     1159
#define IDC_EDIT_W1                     1160
#define IDC_EDIT_H1                     1161
#define IDC_CHECK_SHOW1                 1162
#define IDC_EDIT_X2                     1163
#define IDC_EDIT_Y2                     1164
#define IDC_EDIT_W2                     1165
#define IDC_EDIT_H2                     1166
#define IDC_CHECK_SHOW2                 1167
#define IDC_EDIT_X3                     1168
#define IDC_EDIT_Y3                     1169
#define IDC_EDIT_W3                     1170
#define IDC_EDIT_H3                     1171
#define IDC_CHECK_SHOW3                 1172
#define IDC_EDIT_X4                     1173
#define IDC_EDIT_Y4                     1174
#define IDC_EDIT_W4                     1175
#define IDC_EDIT_H4                     1176
#define IDC_CHECK_SHOW4                 1177
#define IDC_BTN_SETUP1                  1178
#define IDC_BTN_SETUP2                  1179
#define IDC_BTN_SETUP3                  1180
#define IDC_BTN_SETUP4                  1181
#define IDC_EDIT_COLOR1                 1183
#define IDC_EDIT_COLOR2                 1184
#define IDC_EDIT_COLOR3                 1185
#define IDC_EDIT_COLOR4                 1186
#define IDC_BTN_RGB1                    1187
#define IDC_BTN_RGB2                    1188
#define IDC_BTN_RGB3                    1189
#define IDC_BTN_RGB4                    1190
#define IDC_SHOW                        1191
#define IDC_RADIO_COVER1                1192
#define IDC_RADIO_COVER2                1193
#define IDC_DHCP_COMBO                  1193
#define IDC_RADIO_COVER3                1194
#define IDC_DNSMODE_COMBO               1194
#define IDC_RADIO_COVER4                1195
#define IDC_IP_IPADDRESS                1195
#define IDC_SUBNET_IPADDRESS            1196
#define IDC_PDNS_IPADDRESS              1197
#define IDC_SDNS_IPADDRESS              1198
#define IDC_GATEWAY_IPADDRESS           1199
#define IDC_MAC_EDIT                    1200
#define IDC_HTTP_PORT_EDIT              1201
#define IDC_T_EA                        1202
#define IDC_T_EAM                       1203
#define IDC_COMBO_CHANNEL               1204
#define IDC_LIST_WIFI                   1205
#define IDC_CHECK_ENABLE                1206
#define IDC_COMBO_MODE                  1208
#define IDC_COMBO_AUTH                  1209
#define IDC_COMBO_ENC                   1210
#define IDC_EDIT_KEY                    1211
#define IDC_EDIT_KEYCK                  1212
#define IDC_EDIT_SSID                   1213
#define IDC_PROGRESS_S                  1214
#define IDC_PROGRESS_C                  1215
#define IDC_COMBO_STREAM                1216
#define IDC_EDIT_AUINPUT                1218
#define IDC_EDIT_AUOUTPUT               1219
#define IDC_BTN_SETINPUTMODE            1220

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        143
#define _APS_NEXT_COMMAND_VALUE         32771
#define _APS_NEXT_CONTROL_VALUE         1221
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
